--5. MAGNITUDE
--==========================================
-- find total customers by countries
SELECT country, COUNT(DISTINCT customer_key) AS Total_Customers FROM gold.dim_customers
GROUP BY country;
GO

-- find total customers by gender
SELECT gender, COUNT(DISTINCT customer_key) AS Total_Customers FROM gold.dim_customers
GROUP BY gender;
GO

-- find total products by category
SELECT category, COUNT(DISTINCT product_key) AS Total_Products FROM gold.dim_products
GROUP BY category;
GO

-- what is the average cost in each category
SELECT category, AVG(cost) AS avg_product_cost FROM gold.dim_products
GROUP BY category;
GO

-- what is the total revenue generated by each category
SELECT p.category, SUM(f.sales_amount) AS Total_revenue 
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY category;
GO

-- find the total revenue generated by each customer
SELECT DISTINCT c.customer_key, SUM(sales_amount) AS Total_revenue 
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.customer_key;
GO

--- what is the distribution of solid items across countries?
SELECT country, SUM(f.quantity) AS Total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.country;
GO
